ARG REGISTRY=docker.io
FROM ${REGISTRY}/python:3.12

WORKDIR /backend
ENV PYTHONPATH="${PYTHONPATH}:/backend/apps"
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
COPY .env.prod /backend/.env

EXPOSE 8000
# collectstatic выполняется уже ПОСЛЕ монтирования тома
CMD ["bash", "-lc", "python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"]


