ARG REGISTRY=docker.io
FROM ${REGISTRY}/nginx:1.24
COPY nginx.conf /etc/nginx/nginx.conf
COPY stalkraft.conf /etc/nginx/conf.d/stalkraft.conf
COPY certificates/ /etc/nginx/certificates/
COPY frontend/ /usr/share/nginx/html
EXPOSE 80 443
HEALTHCHECK CMD wget -qO- http://localhost/ || exit 1
CMD ["nginx", "-g", "daemon off;"]
