ARG REGISTRY=docker.io
FROM ${REGISTRY}/nginx:1.24
RUN rm -f /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY stalkraft.dev.conf /etc/nginx/conf.d/stalkraft.conf
COPY certificates/ /etc/nginx/certificates/
EXPOSE 80 443
HEALTHCHECK CMD wget -qO- http://localhost/ || exit 1
CMD ["nginx", "-g", "daemon off;"]
